### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ianlulu** [IanLulu/ianlulu.github.io#2]
- [ ] fix collapsible sizing (see alt website's social links format)
- [x] add icons to collapsibles and its contents (?) [finished 14 oct. 2023]
- [ ] edit repo description and readme [possibly finished 14 oct. 2023 but need 2 edit again]
- [x] add og design spec to readme [finished 14 oct. 2023]
- [ ] organize everything into divs
&rarr; also utilize the new html 5 standard `<section>` tags along with `<div>`
- [ ] more documentation, more comments
- [x] custom domain: [finished feb 22&23, 2024]
- sources &rarr; [namecheap](https://nc.me/), [github student](https://education.github.com/pack), [github pages cname](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)
@ 2024-02-26 edit: [add custom domain tutorial](https://youtu.be/rIXWUJ5U8bY?si=xQ6_ppr5qWVpBUit)[1st⏱Feb21]
- notes: [02-26 13:51] added license on 23 feb to follow jvscholz [website_portfolio](https://github.com/jvscholz/website_portfolio)
